### ISSUE TITLE
PCL被微软安全认定为为危险

### ISSUE THREAD

**Issue by BigFish520** [Meloong-Git/PCL#1123]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![微信图片_20230203005257](https://user-images.githubusercontent.com/124289463/216389665-63b4bd88-820b-48f8-abe3-0550eec64732.png)
![微信图片_20230203005300](https://user-images.githubusercontent.com/124289463/216389677-30769845-cb8a-4e0f-a0f9-424e966eb421.png)

### 重现步骤

启动时被微软安全误杀

### 日志与附件

无

**Comment by Hatsushigure** [comment]
不是很早就会误伤了吗

**Comment by youzi-2333** [comment]
见 #666 ，PCL2 快照版不会向微软汇报，而快照版就会被误杀（Windows Defender 有时甚至都不记录 Log），感谢您的反馈~
