### ISSUE TITLE
按键指示错误

### ISSUE THREAD

**Issue by Fangcneng** [Meloong-Git/PCL#1297]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

比较简单，PCL启动器启动页面显示右键点击人物头像查看更多选项，实际要点的是左键，我怀疑猫跃是不是打错了

### 重现步骤

打开PCL启动器启动页面
右键人物头像，显示另存为与刷新，左键则可以

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10772727/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10772728/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10772729/Log4.txt)
[Log1 (2).txt](https://github.com/Hex-Dragon/PCL2/files/10772730/Log1.2.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10772731/Log1.txt)

**Comment by WForst-Breeze** [comment]
没太看懂……qwq……
左键单击头像会直接更换皮肤，右键单击会弹出更多选项，分别为：保存皮肤（另存为），刷新皮肤（刷新），更换披风。
没什么错吧……？

**Comment by youzi-2333** [comment]
~~我用了半年 PCL2 居然没有发现~~已初步确认，感谢您的反馈~

**Comment by Fangcneng** [comment]
好的好的








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 按键指示错误 (Issue #1297)





 
我用了半年 PCL2 居然没有发现已初步确认，感谢您的反馈~

**Comment by WForst-Breeze** [comment]
感谢您的反馈~

**Comment by Fangcneng** [comment]
emm，我这边就左键切到设置，右键另存为和刷新






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 上午9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 按键指示错误 (Issue #1297)





 
没太看懂……qwq……
 左键单击头像会直接更换皮肤，右键单击会弹出更多选项，分别为：保存皮肤（另存为），刷新皮肤（刷新），更换披风。
 没什么错吧……？

**Comment by WForst-Breeze** [comment]
左键切到设置……？皮肤设置吗，本来就是这样的🤔

**Comment by Fangcneng** [comment]
好吧，我的理解问题，谢谢提醒






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 按键指示错误 (Issue #1297)





 
左键切到设置……？皮肤设置吗，本来就是这样的🤔
