### ISSUE TITLE
提供包含DotNet Framework、Java的版本

### ISSUE THREAD

**Issue by I-AM-A-NOOB** [Meloong-Git/PCL#1376]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在原有可执行文件基础上，另行打包一个带运行环境(DotNet Framework+Java 8+Java 17)的版本

### 原因

我很喜欢用游戏荼毒同学，但是由于某些原因，他们的电脑**(Windows 7)**里**没有DotNet Framework**>=4.6，**给他们链接又懒得下载**，然后他们去玩网易了……

按照这个趋势，他们**肯定不知道怎么下Java**……

而网易，**一键配置环境**很方便，但是会导致臃肿（我在用网易时不知道如何设置文件路径

而提供一个官方的**准整合包**，也许可以使得PCL2得到**更加广泛的欢迎和推广**。

**Comment by WForst-Breeze** [comment]
与 #750 重复，感谢您的反馈~

**Comment by Chiloven945** [comment]
java投票已经有了，.net运行库win10/11自带，目前用win10以下都应该已经很少了吧……
