### ISSUE TITLE
自动更新不了

### ISSUE THREAD

**Issue by Chormore-EDGE** [Meloong-Git/PCL#1387]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

无法自动更新（提问才知道）

### 重现步骤

e我也不知道，详情看[https://github.com/Hex-Dragon/PCL2/discussions/1385](url)提的问题

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10882034/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10882036/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10882037/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10882038/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10882039/Log2.txt)

**Comment by YUANXINGlingyun** [comment]
原始 Discussion #1385
已初步确认，感谢您的反馈

**Comment by WForst-Breeze** [comment]
无法复现，请检查您的网络连接状况及网络环境是否良好，一般情况下，这不是 PCL2 的问题，感谢您的反馈~
