### ISSUE TITLE
在PCL内添加主页编辑器

### ISSUE THREAD

**Issue by AstralFlare-owo** [Meloong-Git/PCL#1454]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在自定义主页设置中添加主页编辑器，以图形化界面修改主页布局，让更多人能快速上手自定义主页功能。

### 原因

懒得敲XAML了……

**Comment by YUANXINGlingyun** [comment]
WPF XML 图形化编辑器市面上有很多了
再说之前哪里提过拒绝了来着

**Comment by WForst-Breeze** [comment]
理由同上，感谢您的反馈
