### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by HomoobyDX** [Meloong-Git/PCL#1647]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

有时候新安装的游戏（外面复制文件或者外面导入），单击启动游戏会概率性启动两个游戏（以新型工程：世界整合包为例，启动了两个mcpath服务器更新脚本）

### 重现步骤

1、新安装包，用安装一个纯净forge再导入文件
2、点击微软登录再点击离线（用最快的手速）

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11232685/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11232686/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11232687/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11232688/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11232689/Log5.txt)

**Comment by iPodtouch6557** [comment]
~没微软焯~穿个截图？

**Comment by Chormore-EDGE** [comment]
~~有没有可能是你先点了微软游戏启动了之后快速切换离线启动~~
（不过我很倾向于点了2次

**Comment by hellominecraftlauncher** [comment]
> ~有没有可能是你先点了微软游戏启动了之后快速切换离线启动~ （不过我很倾向于点了2次

日志好像有第一次用微软登录然后取消，第二次又切换到离线

**Comment by iPodtouch6557** [comment]
提个小意见，以后把issue标题改的具体一点，“启动问题“太含糊了

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/232204914-41a91573-dd30-4780-944f-711be7d12131.png)

 应该是在启动进程的同时按了取消导致的

**Comment by hellominecraftlauncher** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/232204914-41a91573-dd30-4780-944f-711be7d12131.png)
> 
> 应该是在启动进程的同时按了取消导致的

可是我在玩别的也偶尔出现这个了（日志早清理了），不知道是核心的问题还是点击时间问题

**Comment by LTCatt** [comment]
与 #1631 重复
