### ISSUE TITLE
1.18.2+中Forge无法加载模组形式OptiFine。

### ISSUE THREAD

**Issue by Wudji** [Meloong-Git/PCL#188]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

~~几个月前反馈过，不过看起来还是没修复（~~
PCL2疑似无法加载高清修复的wrapper，导致无法加载**模组形式的高清修复（指从官网直接下载的那种）**
HMCL等其他启动器可正常加载

### 重现步骤

下载Forge的游戏，然后安装模组形式的高清修复

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9711262/Log1.txt)
视频：

[video.zip](https://github.com/Hex-Dragon/PCL2/files/9711274/video.zip)

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/194621077-c9506159-7dd4-4499-ae63-c9f6748c434d.png)
![image](https://user-images.githubusercontent.com/40348278/194621152-4b791a68-a69f-4793-b037-b75281a34793.png)

测试没有问题。你是不是没有装适配的 Forge 版本……现在 optifine 如果和 forge 版本对不上会出问题，1.18.2_HD_U_H9_pre1 只兼容 Forge 40.1.73，你再看看？
从官网下载之后不是直接放进 mods 文件夹，要先双击打开选择 extract，之后它会生成一个 OptiFine_1.18.2_HD_U_H9_pre1_MOD.jar 文件，它再作为 mod 加载

**Comment by LTCatt** [comment]
经测试 HMCL 不 extract 也加载不了……

**Comment by LTCatt** [comment]
我这里用 HMCL-3.5.3.223 确实也加载不了……
你把你的那个 optifine 的 jar 文件发一下？看看有没有 **其他人** 可以帮忙复现（用 HMCL 能加载，PCL 不能）……
我总觉得这不是我这的问题 =。=

**Comment by Wudji** [comment]
久远的issue，不知道还能不能拿个主题
识别码：2ABD-AFC3-A969-45CF
麻烦大佬了~

**Comment by LTCatt** [comment]
你的解锁码：ihR8z7myDqbrMT3yvp+jXPgF5LVn045O
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
