### ISSUE TITLE
[转自 PCL2HELP] PCL2 加载帮助库失败

### ISSUE THREAD

**Issue by z0z0r4** [Meloong-Git/PCL#194]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

见 https://github.com/LTCatt/PCL2Help/issues/251

### 重现步骤

https://github.com/LTCatt/PCL2Help/issues/251

### 日志与附件

https://github.com/LTCatt/PCL2Help/issues/251

**Comment by LTCatt** [comment]
使用 #196
