### ISSUE TITLE
添加回退上一首音乐功能

### ISSUE THREAD

**Issue by iPodtouch6557** [Meloong-Git/PCL#1981]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

如题
我认为左右键已经满了，再做按键适配要动脑子，暂时选的新功能，龙猫可以根据情况随时换

### 原因

我需要这个功能来切换上一首歌。我听音乐一般是照自己喜好手动切歌的，所以有相关需求，但如果没有这个功能，就不能切换上个歌曲了，要反复右键很多遍（尤其是我这种歌单几十首歌的人），操作会很麻烦。

**Comment by LTCatt** [comment]
算了算了.jpg

**Comment by iPodtouch6557** [comment]
~真 **·** 算了算了~
不过没有也能用，就是按废右键麻烦点就是了awa。感谢受理~
