### ISSUE TITLE
使用"内存优化"功能后重启电脑 启动器本体消失

### ISSUE THREAD

**Issue by Yu-xiaohei** [Meloong-Git/PCL#1985]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

> 懒得排版了，龙猫凑合看吧 ()

当我使用最新快照版(2.6.2)百宝箱中的内存优化功能后
待优化完成释放内存成功后，正常进行游戏
当关闭游戏及启动器时，再次打开启动器任然无异样
但当我 **重启电脑** 后，启动器文件(Plain Craft Launcher 2.exe)就会离奇消失
---
经过测试
不管是否启动游戏，**只要进行内存优化功能，并重启电脑**，启动器文件就会消失
具体原因不明
---
对于一个每很需要这个功能但用一次把自己删一次的功能，球球快修复一下吧
### 重现步骤

1. 任选一个版本启动
2. 带启动并进入地图后返回PCL2
3. 进入`更多`
4. 进入`百宝箱`
5. 点击`内存优化`
6. 待优化完成
7. 继续游戏一段时间
8. 退出游戏及启动器 (正常退出方式)
9. 重启电脑
10. 点击PCL2 (快捷方式)‘’
> 芜湖， 该快捷方式所指向的项目“Plain Craft Launcher 2.exe"已经更改或移动
> 好耶，启动器没啦 [doge]
11. 打开启动器所在目录
> 果然消失喽~
12. 用`everything`搜关键词
> 就只剩个.pf文件了 2333

-- END --

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11665847/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11665849/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11665850/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11665851/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11665852/Log2.txt)

**Comment by LTCatt** [comment]
Defender 删的，详见 #666
