### ISSUE TITLE
服务器连接与检测功能

### ISSUE THREAD

**Issue by xtrackc1437** [Meloong-Git/PCL#1993]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

做一个列表，支持添加自定义服务器和检测服务器motd, 人数, 在线状态 (最好还可以快捷加入)
~~我总觉得有人提过但是gh上没搜到((~~

### 原因

便于玩家快速判断服务器状态和加入服务器

**Comment by bwtx2023** [comment]
个人认为有点太超出启动器的范围了…？

先留着了，看看龙猫怎么说

**Comment by LTCatt** [comment]
超出启动器范畴了，不考虑，抱歉 :/
