### ISSUE TITLE
1.20更新时间错误

### ISSUE THREAD

**Issue by Jingwen178** [Meloong-Git/PCL#2000]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

本版本发布时间应为6月7日，PCL2将他错误地显示为了6月2日

### 重现步骤

1.切换下载页面
2.打开正式版选项

### 日志与附件

<img width="576" alt="无标题" src="https://github.com/Hex-Dragon/PCL2/assets/129640814/52550718-ff54-4c5e-9c04-db02548e9e62">

**Comment by iPodtouch6557** [comment]
重复 #1999 
~恭喜你喜提第2000个issue~
