### ISSUE TITLE
“赞助”里还有“复制识别码”和“输入解锁码”

### ISSUE THREAD

**Issue by blibilijojo** [Meloong-Git/PCL#2130]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

之前我记得修改过这个，确实说的是这个分类的不对（也有可能是记错了），然后移到了 设置/启动器/系统 里，但是在 更多/关于与鸣谢/赞助 里还有“复制识别码”和“输入解锁码”这两个，名不符题了吧，应该把 更多/关于与鸣谢/赞助 里的“复制识别码”和“输入解锁码” 去除。
顺便一提，如果去了应该吧“赞助作者”居中一下调整一下位置。
![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/d2c11bf3-a4a3-41af-a8bd-8b72556317cf)
![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/7336f120-af9b-4c18-aca3-09704ce36470)

### 原因

（示例）
这项优化让我可以更方便地xxxx。
如果没有这项优化，我每次都必须xxxx，让操作变得很麻烦。

**Comment by WForst-Breeze** [comment]
见 #1482 和 [v2.5.2 更新日志](https://github.com/Hex-Dragon/PCL2/releases/tag/2.5.2)：
在系统设置中>>**添加了**<<复制识别码、输入解锁码入口

**Comment by blibilijojo** [comment]
> 见 #1482 和 [v2.5.2 更新日志](https://github.com/Hex-Dragon/PCL2/releases/tag/2.5.2)：
> 
> > 在系统设置中>>**添加了**<<复制识别码、输入解锁码入口

所以为啥添加了还要在赞助里还留下这个，并且照正常的分类来讲这个也不应该属于赞助里的啊，又不是只有金色隐藏会用到这个功能
