### ISSUE TITLE
关闭optifine

### ISSUE THREAD

**Issue by blue-wxy** [Meloong-Git/PCL#214]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在使用PCL2启动某些大型整合包时，由于是导入包，所以用PCL2下载了minecraft游戏本体和optifine。然而，不知道是整合包问题或是其它问题，停止游玩一个月再回坑后进入暮色森林后会在大约5秒后闪退。群友分析有可能是optifine的问题。然而PCL2下载optifine好像很特殊，在mods文件夹中不能找到optifine mod，这让我无法删除optifine。希望您能够提供重新关闭optifine的功能。

### 原因

这项优化能够解决重要的问题。。。。

**Comment by LTCatt** [comment]
重新安装这个版本，然后覆盖 jar 和 json 文件就行……
（ `修改已安装版本的 optifine 和 forge` 应该归属在另外一个功能提案里？但似乎没有？谁去提一个？）

**Comment by Big-Cake-jpg** [comment]
> 重新安装这个版本，然后覆盖 jar 和 json 文件就行…… （ `修改已安装版本的 optifine 和 forge` 应该归属在另外一个功能提案里？但似乎没有？谁去提一个？）

咦？原来PCL2 安装整合包时不是把 OptiFine 以模组形式加载进游戏啊（

**Comment by LTCatt** [comment]
> 咦？原来 PCL2 安装整合包时不是把 OptiFine 以模组形式加载进游戏啊（

根据 PCL2 的版本不同行为不一样（
有的版本是作为 mod 安装的，有的版本不是……
鬼知道他安装的时候用的是哪个版本的 PCL =。=

**Comment by huanhuanll** [comment]
.minecraft\libraries\optifine\OptiFine
在这个文件夹里你能找到你所安装的optifine
![屏幕截图 2023-02-04 200929](https://user-images.githubusercontent.com/122186502/216766885-cdec4f92-f593-467e-9058-b93fad8b5feb.png)

**Comment by dddddgz** [comment]
optifine不是mod吧

**Comment by WForst-Breeze** [comment]
>（ `修改已安装版本的 optifine 和 forge` 应该归属在另外一个功能提案里？但似乎没有？谁去提一个？）

#220 已经包含了吧？

**Comment by zkitefly** [comment]
> optifine不是mod吧

可以看作是模组，因为安装程序可以直接放到 mods 文件夹进行加载

**Comment by dddddgz** [comment]
> .minecraft\libraries\optifine\OptiFine 在这个文件夹里你能找到你所安装的optifine ![屏幕截图 2023-02-04 200929](https://user-images.githubusercontent.com/122186502/216766885-cdec4f92-f593-467e-9058-b93fad8b5feb.png)

貌似删了没用？
