### ISSUE TITLE
增加硬件实时检测

### ISSUE THREAD

**Issue by NebulaTechs** [Meloong-Git/PCL#2235]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

建议在Minecraft运行时监测硬件资源，在电脑硬件负载过大时保存MC数据并强行终止MC，然后提示用户硬件负载过大。
在用户再次启动MC后提示是否加载上次紧急保存的数据（*版本之间不要互串了）。

### 原因

一次惨案：我有一天在玩MC，直接给我蓝屏了（悲）

**Comment by zkitefly** [comment]
这，会不会误判啊，还有实时监测的话会不会影响性能

我觉得龙猫应该不会做的？

**Comment by pangzong2011** [comment]
我感觉没太大意义：（
做起来也比较困难，之前的issues提到过重启pcl2无法关闭mc，好像是无法识别jvav，也不知道实现这个也会不会遇到这个问题（
