### ISSUE TITLE
加载自定义主页失败 调用的目标发生了异常。

### ISSUE THREAD

**Issue by whx404** [Meloong-Git/PCL#2279]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在没有任何我认为可能的触发条件下我自己写的主页突然打不开。
是我的电脑休眠以后我开了电脑再启动了pcl2，然后报错。我尝试生成教学文件，但是教学文件依然显示这个错误。在log里，他有检查我的文件
在issue页面中我搜到了类似的，希望我此次提出能够给予解决。

### 重现步骤

除了电脑休眠，我没有进行任何操作

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12078902/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12078904/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12078906/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12078907/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12078908/Log1.txt)

**Comment by youzi-2333** [comment]
不是，它报错不记录日志的么……

**Comment by whx404** [comment]
> 不是，它报错不记录日志的么…… 感觉和 #1474 类似。

实际上我说的“类似：就是指那个，但是他的好像更详细一些，我的只有一个窗口

**Comment by whx404** [comment]
所以。。。在我误打误撞再次挂着“错误”的pcl2休眠的时候我开机他就好了。。。加载教学文件的log在这里
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12090632/Log5.txt)
但是很明显他跟我的log就是是否有显示窗口的问题。

**Comment by whx404** [comment]
在程序与功能中取消.net framework（所有版本）后确认，再开启功能时会更新组件，重启后恢复正常
