### ISSUE TITLE
在自动安装中添加新的模组加载器NeoForge

### ISSUE THREAD

**Issue by ghost** [Meloong-Git/PCL#2411]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

在自动安装中添加新的模组加载器，NeoForge：https://www.mcmod.cn/class/11433.html
NeoForge是现有Forge的分支，可兼容Forge模组同时运行更好。

### 原因

NeoForge是现有Forge的分支，可兼容Forge模组；
NeoForge不拒绝与 Sponge、Fabric、 Bungeecord、Velocity 等项目展开合作；
NeoForge不阻止第三方启动器自动安装 Neoforge（原 MinecraftForge 明确禁止自动安装，还撤下了metadata源）；
当前 1.20.1 版本保持与原 MinecraftForge 的兼容性。以后的版本会在遵守自己标准的前提下尽量保持兼容性。

**Comment by zkitefly** [comment]
重复啦！！！
