### ISSUE TITLE
1.14.4版本打开失败

### ISSUE THREAD

**Issue by WangZhePanPan** [Meloong-Git/PCL#2511]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [ ] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在打开1.14.4-Fabric 0.14.22-OptiFine_G5时出现错误
（装了在PCL上下载的MOD，但还是问问，自己不懂，谢谢大佬）

### 错误报告、日志与附件

[Uncaught exception in thread main.txt](https://github.com/Hex-Dragon/PCL2/files/12359607/Uncaught.exception.in.thread.main.txt)
[错误报告-2023-8-16_20.42.50.zip](https://github.com/Hex-Dragon/PCL2/files/12359608/-2023-8-16_20.42.50.zip)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12359613/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12359614/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12359615/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12359616/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12359617/Log5.txt)

**Comment by SALTWOOD** [comment]
建议是先去discuss问问

但还是让我先看看.png

**Comment by SALTWOOD** [comment]
似乎与PCL无关哦
装了什么模组
不装还有没有这个bug

**Comment by WangZhePanPan** [comment]
> 似乎与PCL无关哦 装了什么模组 不装还有没有这个问题

刚下载这个版本，玩都没玩过一次，是不是把mod文件去了就没事了？

**Comment by hejiehao** [comment]
Optifabric

**Comment by SALTWOOD** [comment]
经检查在安装optifabric的情况下游戏无法打开
但是删除则能正常打开
你检查项也没勾，模组问题还来投PCL2的issue
关了吧

**Comment by SALTWOOD** [comment]
Close issue
