### ISSUE TITLE
Mod下载功能在指定搜索某版本mod时不显示“指定版本”

### ISSUE THREAD

**Issue by blibilijojo** [Meloong-Git/PCL#2571]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/8b12c3a5-86b5-4d2d-8568-9b8717bbf18b)
![image](https://github.com/Hex-Dragon/PCL2/assets/102420734/d9de08d9-f59b-4779-a449-11022a17bf32)
具体规律不知道，但可以稳定复现。

### 重现步骤

1、点击“下载”中的“Mod”，设置搜索范围为1.16.5的forge
2、搜索“物理掉落”
3、点开物品物理掉落模组（无论是哪一个都行）
4、复现成功

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12409054/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12409056/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12409058/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12409059/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12409060/Log5.txt)

**Comment by SALTWOOD** [comment]
是因为模组作者没设置加载器，其他模组能正常显示说明这是个例
与PCL无关

**Comment by SALTWOOD** [comment]
你去那个模组的curseforge页面看看，如图
![1692713231648](https://github.com/Hex-Dragon/PCL2/assets/105980161/cd285233-ec1f-417f-a335-f0e079e309d5)
可以关
