### ISSUE TITLE
无法正版登录

### ISSUE THREAD

**Issue by MCyuzhouRS** [Meloong-Git/PCL#2707]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在使用正版账号登陆时会卡住并且无法进入，重启，加速器，重装启动器，重置网络等都没有用，只有很小的概率可以登录
![1](https://github.com/Hex-Dragon/PCL2/assets/124948981/7b1c06ec-c4da-445b-8866-c75ecb789033)
![Uploading 2.PNG…]()

### 重现步骤

正版登录，会卡住并且进不去，只有很小的概率可以进去，如果有一次进去了则在没有重启启动器前可以进入

### 日志与附件

没有

**Comment by kong-que-dnf123** [comment]
你可以相信bugjump独有的网络连接（大雾

**Comment by JingHai-Lingyun** [comment]
网络问题
---
题外话 2.png 没传上来
