### ISSUE TITLE
能不能添加一个新建服务器端的功能，类似网上的面板服开服

### ISSUE THREAD

**Issue by XiaokunDong** [Meloong-Git/PCL#2790]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

能不能添加一个新建服务器端的功能，类似网上的面板服开服

### 原因

我需要这个功能来开一个服务器（如：forge版），跟我的小伙伴一起来玩，我相信很多人都有这个需求，我也自己多次尝试部署了，跟着网上的教程也试过了，但是就是不行，又找不到原因，所以请求能搞个一件部署版的。

**Comment by DreamUniverse843** [comment]
龙猫：PCL 是启动器，此功能超出了启动器的范畴。
对应 Issue #108
