### ISSUE TITLE
Release 2.6.10.zip 下载文件被报告为木马：Trojan:MSIL/CryptInject!MSR

### ISSUE THREAD

**Issue by anuxs** [Meloong-Git/PCL#2976]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Windows11操作系统自带的Defendor病毒检测软件一直报告文件有木马，下载后火速被删除，无法保留。
以前的版本下载都没有报告过这个问题。
蓝奏云和百度网盘里面都试过了，Release 2.6.10.zip

### 重现步骤

1、点击[xxxx](https://afdian.net/p/0164034c016c11ebafcb52540025c377)
2、往下滚，然后点击xxxx

### 日志与附件

无

**Comment by JingHai-Lingyun** [comment]
#2928

**Comment by burningtnt** [comment]
大概率是由于旧的构建签名失效的远古，见 #2982

**Comment by JingHai-Lingyun** [comment]
正式版签了

**Comment by JingHai-Lingyun** [comment]
呃 这是什么

**Comment by WorldHim** [comment]
> 搜索了前面的问题。算了吧。这个签名就不想弄一个吗？非要被报告木马还不处理？那真叫人怀疑是否有木马了。

正式版发布才发现的问题，要解决肯定要下个版本啊。程序本身没有问题，难道你不知道 defender 的误报有多严重？
