### ISSUE TITLE
Mod列表多选优化

### ISSUE THREAD

**Issue by HanYuCR** [Meloong-Git/PCL#3049]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

现阶段PCL2的模组列表虽然已经支持多选模组进行批量调整，但是只能一个一个点。这对一些需要一次性整理大量模组的玩家很不友好，所以在此希望龙猫能加入一个类似于在Windows任务管理器里用鼠标框选的功能，并且同时按下Ctrl能够分开多选。如果觉得不平衡可以新增一个按钮，让玩家自己切换模式
(GIF演示如下↓，第一次没有按Ctrl，第二次按住了)
![2023-12-29_1](https://github.com/Hex-Dragon/PCL2/assets/126944908/90371deb-df0b-44cf-8311-943cba8e83a8)

### 原因

见上

**Comment by WorldHim** [comment]
#2333 #2697
