### ISSUE TITLE
mod列表不完整

### ISSUE THREAD

**Issue by XK123furru** [Meloong-Git/PCL#3322]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

加载 Mod 列表 U| 失败:指定的 Visual 已经是另一个 Visual 的子级或者已经是 CompositionTarget 的根在PCL.PageVersionMod.RefreshResult(List 1 Mods)在PCL.PageVersionMod.LoadUFromLoaderOutput()错误类型:System.ArgumentException.
是否反馈此问题?如果不反馈，这个问题可能永远无法得到解决!

### 重现步骤

1、点击版本设置
2、mod管理即会出现描述内容的弹窗

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14269124/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14269125/Log3.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14269128/Log1.txt)

**Comment by zkitefly** [comment]
https://github.com/Hex-Dragon/PCL2/issues/3092
