### ISSUE TITLE
filenotfound

### ISSUE THREAD

**Issue by wuwenjun9939** [Meloong-Git/PCL#3436]
### 检查项

- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我上次在地图崩溃之后就出现这个了
![QQ截图20240227183758](https://github.com/Hex-Dragon/PCL2/assets/110022109/dadb8504-ecdb-426e-8410-b4a331be6f0a)

### 重现步骤

mc地图崩了之后打开pcl2

### 日志与附件

[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14418195/Log5.txt)

**Comment by wuwenjun9939** [comment]
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14418381/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14418383/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14418384/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14418387/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14418388/Log2.txt)

**Comment by wuwenjun9939** [comment]
启动pcl（D:\Game\MC\PCL）文件夹下面的bat是没问题的，但是，pcl和hmcl全部启动失败（pcl显示文件不存在、hmcl显示代码不完整，我猜bakaxl也启动不起来）这就很奇怪了

**Comment by allMagicNB** [comment]
可否使用最新版本复现？

**Comment by wuwenjun9939** [comment]
就是最新版本的pcl2

**Comment by burningtnt** [comment]
不给游戏崩溃信息等于瞎猜
你这是模组的问题

**Comment by allMagicNB** [comment]
我说复现
首先你的所有提交的日志文件没用，**没有一个记载到了错误**
其次，Log4中的版本是`2.6.13`，应该是在这之前触发的 Bug，有可能它在最新版本已经修复了

还有，你的内存太少了，因为它你已经崩了好几次游戏了

**Comment by wuwenjun9939** [comment]
我调到9GB了，再说，如果是模组问题，那么一开始就不可能加载成功

**Comment by wuwenjun9939** [comment]
再说，游戏如果是内存的问题，那么也会加载失败

**Comment by wuwenjun9939** [comment]
hmcl的？

**Comment by wuwenjun9939** [comment]
![QQ截图20240227192522](https://github.com/Hex-Dragon/PCL2/assets/110022109/20e44438-87a7-4b36-876c-742b0959bf73)

**Comment by allMagicNB** [comment]
你还是不懂吗？
# 我说，你这个 Bug 出现的时候是更新前

**Comment by wuwenjun9939** [comment]
那你就试试咯（等我把文件压缩放到网盘上，你自己试试咯）

**Comment by wuwenjun9939** [comment]
正在上传，等一会吧

**Comment by wuwenjun9939** [comment]
https://pan.huang1111.cn/s/R2B9hB，拿去看看啥情况吧

**Comment by kong-que-dnf123** [comment]
```
#于log1 行862~869<日志内的最后一段输出>
[21:34:17] [Client thread/INFO]: [CHAT] §bYour bed protection wish came true!
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000774800000, 253755392, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 253755392 bytes for Failed to commit area from 0x0000000774800000 to 0x0000000783a00000 of length 253755392.
# An error report file with more information is saved as:
# D:\Game\MC\.minecraft\versions\建筑\hs_err_pid8396.log
AL lib: (EE) alc_cleanup: 1 device not closed
```
虽然中间有英文的强调`运行JAVA内存不足`，但我还是不理解JAVA是怎么做到 **`'页面文件太小，无法完成操作'`** 的，~这跟内存有关系吗...?~

**Comment by kong-que-dnf123** [comment]
> [https://pan.huang1111.cn/s/R2B9hB，拿去看看啥情况吧](https://pan.huang1111.cn/s/R2B9hB%EF%BC%8C%E6%8B%BF%E5%8E%BB%E7%9C%8B%E7%9C%8B%E5%95%A5%E6%83%85%E5%86%B5%E5%90%A7)

@wuwenjun9939 题外话：您输入的网盘地址好像把你后面的文字也给转义成地址的一部分了~（虽然自己把文字那一部分删除也没啥大不了的...）~
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/311c9ad8-845d-4932-b0df-74d301877e50)

**Comment by wuwenjun9939** [comment]
> > [https://pan.huang1111.cn/s/R2B9hB，拿去看看啥情况吧](https://pan.huang1111.cn/s/R2B9hB%EF%BC%8C%E6%8B%BF%E5%8E%BB%E7%9C%8B%E7%9C%8B%E5%95%A5%E6%83%85%E5%86%B5%E5%90%A7)
> 
> @wuwenjun9939 题外话：您输入的网盘地址好像把后面的文字也给转义成地址的一部分了 ~（虽然我自己把文字那一部分删除也没啥大不了的...）~ ![image](https://private-user-images.githubusercontent.com/120994373/308193899-311c9ad8-845d-4932-b0df-74d301877e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDI1ODYsIm5iZiI6MTcwOTA0MjI4NiwicGF0aCI6Ii8xMjA5OTQzNzMvMzA4MTkzODk5LTMxMWM5YWQ4LTg0NWQtNDkzMi1iMGRmLTc0ZDMwMTg3N2U1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxMzU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTBkZDNkNDM1MWQ3OGQzNDRkNWM5NjFlYmIxYTYwZGM3OTZiMDliYTNkMWY5NmNjMDgzOWY0MTViMjI2ODM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WAvJzC-Nr8jJSqu3WccYzRKFFapsYxIgccsGJKf9-4)

怎么说呢，其实吧，我也不知道他咋判定的，也不能怪我啊

**Comment by deep-dark-forest** [comment]
> > > [https://pan.huang1111.cn/s/R2B9hB，拿去看看啥情况吧](https://pan.huang1111.cn/s/R2B9hB%EF%BC%8C%E6%8B%BF%E5%8E%BB%E7%9C%8B%E7%9C%8B%E5%95%A5%E6%83%85%E5%86%B5%E5%90%A7)
> > 
> > 
> > @wuwenjun9939 题外话：您输入的网盘地址好像把后面的文字也给转义成地址的一部分了 ~（虽然我自己把文字那一部分删除也没啥大不了的...）~ ![image](https://private-user-images.githubusercontent.com/120994373/308193899-311c9ad8-845d-4932-b0df-74d301877e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDI1ODYsIm5iZiI6MTcwOTA0MjI4NiwicGF0aCI6Ii8xMjA5OTQzNzMvMzA4MTkzODk5LTMxMWM5YWQ4LTg0NWQtNDkzMi1iMGRmLTc0ZDMwMTg3N2U1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxMzU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTBkZDNkNDM1MWQ3OGQzNDRkNWM5NjFlYmIxYTYwZGM3OTZiMDliYTNkMWY5NmNjMDgzOWY0MTViMjI2ODM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WAvJzC-Nr8jJSqu3WccYzRKFFapsYxIgccsGJKf9-4)
> 
> 怎么说呢，其实吧，我也不知道他咋判定的，也不能怪我啊

链接后要加空格

**Comment by zkitefly** [comment]
> ```
> #于log1 行862~869<所谓MC日志内的最后一段输出>
> [21:34:17] [Client thread/INFO]: [CHAT] §bYour bed protection wish came true!
> OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000774800000, 253755392, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
> #
> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 253755392 bytes for Failed to commit area from 0x0000000774800000 to 0x0000000783a00000 of length 253755392.
> # An error report file with more information is saved as:
> # D:\Game\MC\.minecraft\versions\建筑\hs_err_pid8396.log
> AL lib: (EE) alc_cleanup: 1 device not closed
> ```
> 
> 虽然中间有英文的强调`运行JAVA内存不足`，但我还是不理解JAVA是怎么做到 **`'页面文件太小，无法完成操作'`** 的，~这跟内存有关系吗...?~

在桌面右键此电脑 -- 属性 -- 高级系统设置，然后按图里的顺序改成「自动管理所有驱动器分页文件大小」，改完后点三个「确定」，不要点右上角的叉，重启电脑 ![](https://img.kookapp.cn/assets/2023-03/bGbLMNRnws1020j1.png)

**Comment by wuwenjun9939** [comment]
> > ```
> > #于log1 行862~869<所谓MC日志内的最后一段输出>
> > [21:34:17] [Client thread/INFO]: [CHAT] §bYour bed protection wish came true!
> > OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000774800000, 253755392, 0) failed; error='页面文件太小，无法完成操作。' (DOS error/errno=1455)
> > #
> > # There is insufficient memory for the Java Runtime Environment to continue.
> > # Native memory allocation (mmap) failed to map 253755392 bytes for Failed to commit area from 0x0000000774800000 to 0x0000000783a00000 of length 253755392.
> > # An error report file with more information is saved as:
> > # D:\Game\MC\.minecraft\versions\建筑\hs_err_pid8396.log
> > AL lib: (EE) alc_cleanup: 1 device not closed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 虽然中间有英文的强调`运行JAVA内存不足`，但我还是不理解JAVA是怎么做到 **`'页面文件太小，无法完成操作'`** 的，~这跟内存有关系吗...?~
> 
> 在桌面右键此电脑 -- 属性 -- 高级系统设置，然后按图里的顺序改成「自动管理所有驱动器分页文件大小」，改完后点三个「确定」，不要点右上角的叉，重启电脑 ![](https://camo.githubusercontent.com/f2ab3a73f833e6e0539adf631d00252d0654f3b8a6beb75f8da6e4b7fa827881/68747470733a2f2f696d672e6b6f6f6b6170702e636e2f6173736574732f323032332d30332f6247624c4d4e526e7773313032306a312e706e67)

您是win10吧？我11

**Comment by kong-que-dnf123** [comment]
>您是win10吧？我11

@wuwenjun9939 控制面板能搜到，就叫“查看高级系统设置”

**Comment by wuwenjun9939** [comment]
![QQ截图20240228151645](https://github.com/Hex-Dragon/PCL2/assets/110022109/0f221652-078d-4036-8a26-711c7016fe20)
你说的是这个吗？我没动过啊

**Comment by LTCatt** [comment]
主楼提到的 issue 应当是一个奇怪的系统问题，导致 PCL 无法获取其自身的信息，这个我没法修 :/
如果没有其他问题的话就关了吧……

**Comment by allMagicNB** [comment]
都一周了，Author 都没反应……
关了关了¯\\(ツ)/¯
