### ISSUE TITLE
增加MOD描述翻译

### ISSUE THREAD

**Issue by lixingyu41** [Meloong-Git/PCL#3439]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在下载MOD界面对MOD的描述自动翻译为中文

### 原因

能够更方便的了解某些没见过的模组是做什么用的

**Comment by JingHai-Lingyun** [comment]
#2819 已被拒绝，抱歉。
