### ISSUE TITLE
安装自定义整合包时，报错forge

### ISSUE THREAD

**Issue by cleverboy1066** [Meloong-Git/PCL#3476]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我在安装Chroma Sky 2整合包时，在下载时出现报错，多次尝试无果

### 重现步骤

1、讲整合包拖到pcl
2、自动安装，等到进度90%左右报错

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14469362/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14469363/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14469364/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14469365/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14469366/Log5.txt)

**Comment by deep-dark-forest** [comment]
上传下整合包文件

**Comment by allMagicNB** [comment]
```
[20:30:52.569] [System] 接受文件拖拽：C:\Users\1066\Desktop\picture.zip 等 1 个文件
```
哥，你这在装啥？

**Comment by allMagicNB** [comment]
你交的日志全都没用，请复现后请不要打开PCL2 5 次或更多次，在第一时间提交日志

**Comment by HomoobyDX** [comment]
他这个问题属于概率学说，我这试了几次才出现一次，并且其他启动器都能正常安装,PCL就框框出问题，不是forge安装器失败就是MD5校验过不去

**Comment by kong-que-dnf123** [comment]
>他这个问题属于概率学说，我这试了几次才出现一次，并且其他启动器都能正常安装,PCL就框框出问题，不是forge安装器失败就是MD5校验过不去

那那那没法稳定复现的话也不好修的说啊....

**Comment by rumengchuxing062** [comment]
两周了
coll过来关下?

**Comment by zkitefly** [comment]
超时关闭
