### ISSUE TITLE
添加导入或打开我的世界基岩版，我的世界地下城，我的世界传奇的按钮。

### ISSUE THREAD

**Issue by BananaTennise** [Meloong-Git/PCL#3498]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

添加导入或打开我的世界基岩版，我的世界地下城，我的世界传奇的按钮。从官方启动器导入三者的快捷方式并在PCL2中启动。

### 原因

我需要这个功能来避免网络问题打开官方启动器的难题。很多人都有都因为网络问题进入官方启动器很不方便且官启对JAVA版的mod下载和安装没有pcl2方便，但如果没有这个功能，就要反复切换启动器并且体验不好。

**Comment by allMagicNB** [comment]
不对啊，这本质上不还是支持启动吗？

**Comment by i486-DX9** [comment]
滚去官方启动器

**Comment by Ad-closeNN** [comment]
> 滚去官方启动器

请友好交流，谢谢

**Comment by wuliaodexiaoluo** [comment]
>滚去官方启动器

请保持友好的语气，另外没事请勿乱挖坟
