### ISSUE TITLE
在Mac上通过wine启动时闪退

### ISSUE THREAD

**Issue by wss2wqs** [Meloong-Git/PCL#3524]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在Mac上通过wine启动时闪退

### 重现步骤

通过wine打开

### 日志与附件

无

**Comment by JingHai-Lingyun** [comment]
PCL 基于 WPF，所以不支持除了 Windows 以外的系统

**Comment by wuyuncheng-26** [comment]
Wine 别想了

**Comment by wuliaodexiaoluo** [comment]
PCL 不会对Wine环境提供任何支持，因为 Wine 属于非标准 Windows 环境

**Comment by hejiehao** [comment]
试图使用 Wine 在 Linux 上运行 PCL2，结果废了
