### ISSUE TITLE
不确定你们反馈了没

### ISSUE THREAD

**Issue by wuwenjun9939** [Meloong-Git/PCL#3554]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/2feeaf64-29e3-4eb7-aa72-3dd3ddb54233)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/235ed337-9b88-4eda-b5cb-9d67e6152faf)

### 重现步骤

不知道什么时候会卡文件夹（本来安装过24w12a，不显示，估计重启之后才显示）

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14730577/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14730579/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14730580/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14730581/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14730582/Log2.txt)

**Comment by allMagicNB** [comment]
下面那个 `不常用版本` 展开看看？

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/55cc3145-0afc-4a37-9645-d012f722d5e0)

**Comment by allMagicNB** [comment]
全展开找找吧……

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/82bd6bae-f5d0-4dbd-82bf-d9e847f0ab48)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/2f6fa9a6-3247-479b-b9b7-f6931d975bed)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/3f921415-ce2a-4b9b-9318-11ccb163f3a5)
这就很奇怪，文件夹里面明明有，pcl2就是不显示

**Comment by allMagicNB** [comment]
不对，你会不会装到其他 `.minecraft` 文件夹里了吧……

**Comment by allMagicNB** [comment]
你文件夹点进去截屏发出来

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/3ee428f5-e705-4f20-917a-8bbfce3f24f6)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/1d26d5e2-87f8-48fa-b4ef-6fee9f4b7393)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/044bb06c-a81d-4139-94c8-d67509761a3c)

**Comment by allMagicNB** [comment]
不是，我是指 `24w12a` 那个文件夹

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/b032968b-c74e-4e98-a0c5-2c8697810266)

**Comment by wuwenjun9939** [comment]
而且，如果出错的话，他就会在pcl2里面显示一个“错误的版本”，并提示为啥错

**Comment by allMagicNB** [comment]
要不把这个文件夹传上来？

**Comment by wuwenjun9939** [comment]
[24w12a.zip](https://github.com/Hex-Dragon/PCL2/files/14730617/24w12a.zip)
因为pcl文件夹是随着pcl2启动而启动的，所以没上传

**Comment by wuwenjun9939** [comment]
现在倒是识别到24w12a了，24w11a没了.....就很迷
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/e5efc2bf-37a6-4686-98f4-fa15104dd2fc)

**Comment by wuwenjun9939** [comment]
不好意思，11a在不常用里面

**Comment by allMagicNB** [comment]
应该要有稳定复现方式才能修……

**Comment by wuwenjun9939** [comment]
常规版本达到9个之后，pcl就无法识别第十个（可能）

**Comment by wuwenjun9939** [comment]
因为，我刚下了个10a，pcl又没识别到：
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/082bf47e-189f-46ca-8225-2abb8d2f72e9)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/03f4e2ab-7696-4257-ba8d-d23c7878c642)

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/bb0d5e40-98fd-4574-88bb-6540abae79ce)

**Comment by allMagicNB** [comment]
未能复现……
有可能是个人硬件原因

**Comment by allMagicNB** [comment]
好了，确认为#2781

**Comment by wuliaodexiaoluo** [comment]
复现成功
![image](https://private-user-images.githubusercontent.com/160083863/316229295-b772bd63-f3c5-4d26-b19d-f5a1e1a77b66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODM4MTksIm5iZiI6MTcxMTE4MzUxOSwicGF0aCI6Ii8xNjAwODM4NjMvMzE2MjI5Mjk1LWI3NzJiZDYzLWYzYzUtNGQyNi1iMTlkLWY1YTFlMWE3N2I2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwODQ1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDViN2YwNzMxZmQ3ZTZhYjNhNjJhMTU3ZTAyNjNhNTA1NmM5OGZlOWU2Nzk5ZTA4YWU0YzQyZmRkNTRiOGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jq3PheekxXhjTxIowUUYSG99x1K-UQyo_mwa-EN527Q)
![image](https://private-user-images.githubusercontent.com/160083863/316229314-54896769-790a-4593-9169-224032c24532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODM4MTksIm5iZiI6MTcxMTE4MzUxOSwicGF0aCI6Ii8xNjAwODM4NjMvMzE2MjI5MzE0LTU0ODk2NzY5LTc5MGEtNDU5My05MTY5LTIyNDAzMmMyNDUzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwODQ1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTkwZDYwNmQ2ZTMzMjdkMDRlMTgyNzQ2MjIyM2IyNmQxN2UzYmI1NTAzYWJhYjhmZDljMWM4ODk5MjJjNWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S9gRsojbnm9Hv9s5IHbnFz6fCMzLg78zJj3jPwDcwN0)
[log1](https://github.com/Hex-Dragon/PCL2/files/14730836/Log1.txt)

这是个极其严重的恶性 Bug，因为尝试了包括复制粘贴，重启启动器删除 PCL 文件夹，刷新均不能识别到版本

复现操作为：下载多个版本，在完成下载前点击关闭按钮，点确定推出，下次启动就识别不到版本文件夹

**Comment by allMagicNB** [comment]
后续转到#2781
