### ISSUE TITLE
搜索模组超时后点击中间的“网络环境不佳，请重试或尝试使用VPN”后显示“没有符合条件的结果”而非重新加载模组列表

### ISSUE THREAD

**Issue by LDTchara** [Meloong-Git/PCL#3572]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

如标题所述，且再次点击“没有符合条件的结果”后仍显示“没有符合条件的结果”

### 重现步骤

1、需要断网或网络环境差条件
2、在下载界面中的mod标签页中进行第一次搜索
3、出现“网络环境不佳，请重试或尝试使用VPN”
4、点击“网络环境不佳，请重试或尝试使用VPN”
5、出现“没有符合条件的结果”，并且没有重新加载模组列表，且再次点击“没有符合条件的结果”后仍重复出现“没有符合条件的结果”

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14760764/Log1.txt)

**Comment by LDTchara** [comment]
这个问题在出现“网络环境不佳，请重试或尝试使用VPN”后就算网络恢复良好也仍然存在

**Comment by allMagicNB** [comment]
个人网络原因，非启动器原因，可以尝试使用 HMCL/BakaXL 试试？

**Comment by LDTchara** [comment]
所以这是...特性？？

**Comment by allMagicNB** [comment]
能算是吧……
