### ISSUE TITLE
将启动器版本由2.3.2升级到2.4.2时，无论是否打开防火墙，都会显示安装被防火墙拦截

### ISSUE THREAD

**Issue by f4wt4vymrur76** [Meloong-Git/PCL#363]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [ ] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [x] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

首先在启动器内部点击“检查更新”，
然后提示需要更新，点击下载，
下载完成进行安装时，会弹出一个错误
<img width="391" alt="360截图20221111154806317" src="https://user-images.githubusercontent.com/117972834/201291905-ed9b3709-e6e1-43f4-ae6c-e37666a7e95a.png">
窗口，<img width="391" alt="360截图20221111154806317" src="https://user-images.githubusercontent.com/117972834/201291905-ed9b3709-e6e1-43f4-ae6c-e37666a7e95a.png">
无论如何按照窗口提示操作，都没有用。

### 重现步骤

只要按照上述操作反复操作，最后一定会出现这个窗口！
<img width="391" alt="360截图20221111154806317" src="https://user-images.githubusercontent.com/117972834/201292492-acbd1bc7-ab3a-4948-bd86-402b1b129b1a.png">

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/9988018/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/9988021/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/9988022/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9988023/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9988024/Log2.txt)

**Comment by f4wt4vymrur76** [comment]
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9988194/Log1.txt)
这是最新的log1文件

**Comment by LTCatt** [comment]
这个没办法，我真的没办法……
