### ISSUE TITLE
任何MOD版本下载失败

### ISSUE THREAD

**Issue by xiaoxing2009** [Meloong-Git/PCL#3670]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动安装下载游戏版本除原版外任何MOD加载器就会下载失败
 
错误提示：下载原版 失败 → 获取原版 json 文件下载地址失败 → 无对应的 json 下载地址    在 PCL.ModDownload.DlSourceLauncherOrMetaGet(String MojangBase)    在 PCL.ModDownloadLib._Closure$__6-0._Lambda$__0(LoaderTask`2 Task)    在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()

### 重现步骤

1、点击下载
2、然后点击自动安装
３、选择任何MOD版本

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14949824/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/14949826/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/14949828/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/14949829/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/14949830/Log5.txt)

**Comment by Ad-closeNN** [comment]
#3657

**Comment by allMagicNB** [comment]
确实有重复，但是描述里面的错误是哪来的……

**Comment by xiaoxing2009** [comment]
还在恶性循环每次打开都一样

**Comment by wuliaodexiaoluo** [comment]
实际上你就算安装成功了也没办法用，因为 OptiFine 的 Mod.toml 声明了一个 不存在的类 ```@Mod("OptiFine")``` 根本加载不了

**Comment by xiaoxing2009** [comment]
> 实际上你就算安装成功了也没办法用，因为 OptiFine 的 Mod.toml 声明了一个 不存在的类 根本加载不了`@Mod("OptiFine")`

有没有可能我根本就没安装OptiFine而是仅安装了Forge

**Comment by allMagicNB** [comment]
> > 实际上你就算安装成功了也没办法用，因为 OptiFine 的 Mod.toml 声明了一个 不存在的类 根本加载不了`@Mod("OptiFine")`
> 
> 有没有可能我根本就没安装OptiFine而是仅安装了Forge

她是指你某次测试中下载的版本带有 Optifine

**Comment by xiaoxing2009** [comment]
> > > 实际上你就算安装成功了也没办法用，因为 OptiFine 的 Mod.toml 声明了一个 不存在的类 根本加载不了`@Mod("OptiFine")`
> > 
> > 
> > 有没有可能我根本就没安装OptiFine，而是仅安装了Forge
> 
> 她是指你某次测试中下载的版本带有 OptiFine


好的明白
