### ISSUE TITLE
无法安装 LiteLoader

### ISSUE THREAD

**Issue by Lucier310** [Meloong-Git/PCL#386]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

下载的时候如果一选择带有Liteloader的端的时候就会提示下载不了

具体提示的内容：该字符串未被识别为有效的DateTime。→安装新Liteloader版本失败→安装Liteloader失败→下载Liteloader <版本号> 失败

其它启动器下载这个是正常的

但是PCL下载这个就会出错

识别码：3B9F-EC87-2EC7-67E7

### 重现步骤

1、点击下载
2、往下滚，然后点击<游戏版本号（1.12.2以下）>
3、添加optifine和forge之后往下滚选择点击了Liteloader选项
4、点击了Liteloader的安装选项
5、往上滚点击开始安装
6、出现安装失败提示：该字符串未被识别为有效的DateTime。→安装新Liteloader版本失败→安装Liteloader失败→下载Liteloader <版本号> 失败

### 日志与附件

![QQ截图20221112233821](https://user-images.githubusercontent.com/91145820/201694352-dc772dd2-9107-4825-ae78-68b1a9336d2e.png)

**Comment by Xiaoganghei** [comment]
同样，我已进行反馈，但目前并未处理
-小刚嘿

**Comment by Xiaoganghei** [comment]
……我又搞过来一张图
![image](https://user-images.githubusercontent.com/118163634/202634305-a3771b61-944f-40a6-ac27-097037246f81.png)

**Comment by Xiaoganghei** [comment]
提示，在1.12.2版本中哪怕不安装forge等东西时也会出现这种情况……我一开始真的以为时我的问题 
阿这.jpg

**Comment by Xiaoganghei** [comment]
为什么还是不好使，需要等到下次更新吗？……

**Comment by Lucier310** [comment]
> 为什么还是不好使，需要等到下次更新吗？......

废话，不然你以为lm能给你远程施法然后这个功能就突然好了嘛

**Comment by Xiaoganghei** [comment]
az
我以为他会直接重启时自动更新
