### ISSUE TITLE
关于Mod方面和Mojang登录的新功能建议

### ISSUE THREAD

**Issue by Chormore-EDGE** [Meloong-Git/PCL#389]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

移除Mojang登录选项，换成第三方登录，同时在下载-Mod选项中把部分支持汉化的mod名称汉化，添加一些mod，有时mod搜不到
添加mod时如果mod重复 给出重复提示同时再给出“删除   打开mod文件夹 我知道了‘

### 原因

我需要在第三方登录时的便捷，不然还要麻烦的点一堆选项，mojang登录已经被微软抛弃。
汉化可以让下载者明白XXXmod是干什么的，有什么用，有一些在博主推荐的mod中在PCL II中依然欠缺
在添加mod时很容易添加重复，有了这个提示可以让使用者知道：“我可能加了重复的mod”

**Comment by bwtx2022** [comment]
请分开提两个 Issues

**Comment by bwtx2022** [comment]
部分内容与 https://github.com/Hex-Dragon/PCL2/discussions/43#discussioncomment-3965417 重复

**Comment by Chormore-EDGE** [comment]
我知晓了
