### ISSUE TITLE
自定义主题颜色允许调整 RGB、HSL 等

### ISSUE THREAD

**Issue by BXWGJBGM** [Meloong-Git/PCL#401]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

设置-个性化-基础中的自定义主体我认为可以添加更多颜色选择方式（RGB,HSL或HEX）

### 原因

这项优化让使用者可以更方便地切换主题颜色，而不是调整数值调整半天还调不到自己想要的主题颜色

**Comment by LTCatt** [comment]
这个是自动适配的问题，PCL 会根据数据来自动算出一系列明暗不同的颜色，所以不允许手动输入颜色值。
