### ISSUE TITLE
加载版本列表卡到了别的页面的中央

### ISSUE THREAD

**Issue by LightRainStudio** [Meloong-Git/PCL#4099]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/111848666/89071f8f-6a02-4771-852a-e9490e3a4bcd)
如图，“加载版本列表”这一框卡在了mod下载列表的后面，并且可以随列表的展开向下移动

### 重现步骤

1、点击某个mod的下载页面
2、往下滚，然后在页面中间即可发现错位的“加载版本列表”框

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/15973906/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/15973907/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/15973908/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/15973909/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/15973910/Log1.txt)

**Comment by allMagicNB** [comment]
#1624
