### ISSUE TITLE
与爱发电相关的跳转链接过时

### ISSUE THREAD

**Issue by TheXiaoma** [Meloong-Git/PCL#4384]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

由于爱发电主域更改为"afidian.com"，而PCL2内原有的跳转到爱发电的链接(如:"更多—关于与鸣谢—赞助作者")均错误地跳转到了爱发电原域"afidian.net"，从而造成原本设计的功能因网页无法打开而无法使用

### 重现步骤

点击相应跳转按钮

### 日志与附件

None

**Comment by JingHai-Lingyun** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4271


下次更新将解决这个问题。

**Comment by allMagicNB** [comment]
瞎
