### ISSUE TITLE
错误日志导出失败

### ISSUE THREAD

**Issue by Strange-cmd** [Meloong-Git/PCL#4550]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

试了3次都是导出失败

### 重现步骤

1、点击开始游戏
2、然后点击导出错误报告

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16658246/Log1.txt)

[Log2.txt](https://github.com/user-attachments/files/16658241/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16658242/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16658244/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16658245/Log5.txt)

**Comment by wuyuncheng-26** [comment]
与 #4534 重复
