### ISSUE TITLE
最新快照（2.8.4）其他-关于与鸣谢-特别鸣谢-bangbang93-赞助镜像源打开网页仍为https://afdian.net

### ISSUE THREAD

**Issue by zzr-shift** [Meloong-Git/PCL#4598]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

.net改为.com

### 原因

我想赞助qwq

**Comment by lactobionicAcid** [comment]
与 #4532 重复，请等待下一个快照更新。
赞助bangbang93请前往[该链接](https://afdian.com/a/bangbang93)。

**Comment by SALTWOOD** [comment]
#4532 ，重复，关罢
