### ISSUE TITLE
切回窗口时出错：给定关键字不在字典中

### ISSUE THREAD

**Issue by Seungmin922** [Meloong-Git/PCL#4674]
### 检查项

- [ ] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

删除模组后就没怎么动了

### PCL 错误报告、日志与附件

[Log5.txt](https://github.com/user-attachments/files/16828964/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/16828965/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16828967/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16828968/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16828969/Log4.txt)
![PixPin_2024-09-01_20-54-17](https://github.com/user-attachments/assets/5160a4e5-2f30-4cfa-9247-19cb195e437b)

**Comment by jewel3034** [comment]
版本是最新的快照版本2.8.5
