### ISSUE TITLE
程序出现未知错误：索引必须位于该列表的界限内。

### ISSUE THREAD

**Issue by ExpertLotus9989** [Meloong-Git/PCL#4860]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在较多Mod的情况下在Mod管理禁用后启用mod导致崩溃

### 重现步骤

1、进入Mod管理
2、禁用两个或更多mod
3、搜索其中一个mod的名称并启用
4、再启用另一个mod

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/17198088/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17198089/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/17198090/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17198091/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17198092/Log1.txt)

**Comment by allMagicNB** [comment]
？这 Label？
