### ISSUE TITLE
对一个项的两个不同信息源进行搜索时可能遗漏搜索结果

### ISSUE THREAD

**Issue by ChenXi094** [Meloong-Git/PCL#4912]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

如题
除了常规的添加一个下拉勾选菜单 或许也可以通过在搜索框支持tag=?格式的表达式进行类似功能的实现？

### 原因

起因是面对一个未知来源的大型整合包，我无法直观且快速地了解到其mod的构成。当查阅该整合包使用了那些魔改mod对游戏进行修改时，只能通过浏览全部mod并分别记下每个魔改mod的对应名称。这十分耗时且抽象。
既然Mod下载页面有类似的功能 那在Mod管理页面添加上同样功能也很正常吧（笑）
btw如果我漏看了议题导致该请求重复，十分抱歉。

**Comment by xxtg666** [comment]
🤔已经有了吧 #2953

**Comment by xxtg666** [comment]
现在好像不支持搜索 tag 的同时搜索名称，也不算重复

**Comment by LTCatt** [comment]
![image](https://github.com/user-attachments/assets/f7fc5d39-f6f7-4c86-8d5d-4ef0bff89cf2)
