### ISSUE TITLE
在个性化中加入组件透明度(与颜色)设置

### ISSUE THREAD

**Issue by ThendJyc** [Meloong-Git/PCL#4921]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在PCL页面中
不论使用什么主题
所有组件的保持白色半透明
<img width="224" alt="png" src="https://github.com/user-attachments/assets/3797f58f-6f82-4878-857a-0c6d52c5d5c1">
所以我就想到加入对组件的透明度和主题色设置

### 原因

我想把这玩意染成绿的！
：3

**Comment by Deep-Dark-Forest** [comment]
#2918
> 文本及内容白底可自定义颜色/透明度/添加模糊效果

**Comment by E0x72-21** [comment]
> #2918
> 
> > 文本及内容白底可自定义颜色/透明度/添加模糊效果

确实重复了，但怎么和一个已忽略的issue绑在一起了，难道是不打算采纳这个建议了吗？

**Comment by zhuluzyy** [comment]
赞成，顶

**Comment by zhuluzyy** [comment]
@Deep-Dark-Forest 按照[burningtnt](https://github.com/burningtnt)在#2918 中的建议，其实是从#2918 拆出本issue。不应该标为重复

**Comment by zhuluzyy** [comment]
![Image](https://github.com/user-attachments/assets/3762a97e-94d0-48f8-9737-cb0c44880d04)

另外在背景很乱的时候能让人看清楚字

**Comment by Deep-Dark-Forest** [comment]
> @Deep-Dark-Forest 按照[burningtnt](https://github.com/burningtnt)在#2918 中的建议，其实是从#2918 拆出本issue。不应该标为重复

这两个 Issue 之间已经隔了一年多，而且还不是一个人交的，我不认为这是从 #2918 中拆出来的
同时，龙猫在 https://github.com/Hex-Dragon/PCL2/issues/2918#issuecomment-1833445236 里表示，#2918 里面的所有提议全都不会制作，所以可以认为此 Issue 与 #2918 重复。

**Comment by Deep-Dark-Forest** [comment]
> > #2918
> > 
> > > 文本及内容白底可自定义颜色/透明度/添加模糊效果
> 
> 确实重复了，但怎么和一个已忽略的issue绑在一起了

这是正常现象，一个 issue 与一个“忽略”标签的 issue 重复是一个很正常的事情。

> 难道是不打算采纳这个建议了吗？

参见 https://github.com/Hex-Dragon/PCL2/issues/2918#issuecomment-1833445236
