### ISSUE TITLE
部分光影出现贴图突脸效果

### ISSUE THREAD

**Issue by snystime** [Meloong-Git/PCL#4923]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用iris光影加载器加载iterationT 3.0.0光影时出现贴图突脸效果

### 重现步骤

1、下载1.20.1，fabic端，B站下载iterationT 3.0.0，下载iris模组
2、启动游戏加载iterationT 3.0.0光影，全屏泛白，部分光影也会有相同效果

### 日志与附件

[Log4.txt](https://github.com/user-attachments/files/17278487/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/17278488/Log5.txt)
[Log1.txt](https://github.com/user-attachments/files/17278490/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/17278491/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/17278492/Log3.txt)

**Comment by tangge233** [comment]
那和启动器没关系（
