### ISSUE TITLE
调整页面大小时视角剧烈抖动

### ISSUE THREAD

**Issue by leipishu** [Meloong-Git/PCL#4969]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在调整启动器界面时，整个窗口和内部包括按钮，文字等都会剧烈抖动

### 原因

这项优化让我可以更方便地调整页面大小

**Comment by LTCatt** [comment]
WPF 限制，无法修复
