### ISSUE TITLE
支持自动更新 Mod

### ISSUE THREAD

**Issue by LTCatt** [Meloong-Git/PCL#52]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

支持检查 Mod 的更新，并且在有更新的时候可以自行选择更新哪些，然后一键更新。

### 原因

我个人是不建议这样做的，无脑更新 Mod 版本**很可能**会导致存档不兼容，或者出现更新后无法启动等等问题……

但是既然总有人说需要，那我总之丢一个投票在这里 =。=

**Comment by LTCatt** [comment]
啊，说实话，我还是完全没搞懂为啥想要这功能，谁来解释一下.jpg
瞎更新 Mod 不是必定起飞么（run

其次，我也 **完全不知道** 我要怎么从一个已经下载好的 Mod 文件里获取它到底是 CurseForge 的哪个工程……
在谁知道这个技术问题怎么解决之前我是不知道这得咋做的……

**Comment by abcdesteve** [comment]
> 啊，说实话，我还是完全没搞懂为啥想要这功能，谁来解释一下.jpg 瞎更新 Mod 不是必定起飞么（run
> 
> 其次，我也 **完全不知道** 我要怎么从一个已经下载好的 Mod 文件里获取它到底是 CurseForge 的哪个工程…… 在谁知道这个技术问题怎么解决之前我是不知道这得咋做的…… 谁来解释下原理也好啊，我是真的搞不懂（悲

1. 关于为什么要更新mod
    主要是强迫症看着forge提示很难受
    然后新mod新功能，同mc版本应该没有那么容易崩吧！？
2. 示例
    https://github.com/kaniol-lck/modmanager
    这个作者弃坑了，主要是curse forge改接口之后没更新才用不了，识别mod的功能还是可以的，要不参考一下
3. 建议
    如果  示例  不行的话可以考虑让玩家第一次用的时候手动用PCL2搜mod，然后加入收藏？或者加入一个列表，可以禁止玩家自己改名这样方便绑定（反正不用这个功能的改名也没有影响），每次打开PCL2时搜索mod列表，检测更新，弹窗提醒下载（旧mod在后面加 .old 后缀）

**Comment by lvjiajjjlzy** [comment]
建议不要搞，有MOD可以实现，没用

**Comment by bwtx2022** [comment]
更新完 Mod 以后游戏炸了又要来找 PCL2 回滚什么的，感觉还不如不加

但是考虑到部分 Mod 可能有联网需求，可能会有安全风险，又需要加一下

总之我觉得优先级不是很高

**Comment by Yizhouuu** [comment]
可以参考mod manager(没有适配最新curseforge的api)，我觉得这个主要还是模组太多的时候，要一个一个去查更新太麻烦了，新版本有新的内容还有BUG修复，很多玩家都是几百个模组

**Comment by Yizhouuu** [comment]
> 可以参考mod manager(没有适配最新curseforge的api)，我觉得这个主要还是模组太多的时候，要一个一个去查更新太麻烦了，新版本有新的内容还有BUG修复，很多玩家都是几百个模组

这种软件有好几个，但目前没有能用的，HMCL的这个功能也不完善。我觉得如果启动器集成了这个功能确实很伟大，但是就太臃肿了

**Comment by xxtg666** [comment]
不建议做，mod manager更新的时候不会检查mod对应的版本，经常炸，而且自动更新之后要是启动不了那还会被甩锅给PCL，大型整合包一般也不会去更新mod，没什么必要

**Comment by abcdesteve** [comment]
> 建议不要搞，有MOD可以实现，没用

什么mod？给个链接？

**Comment by LTCatt** [comment]
那来投个票？觉得可以 reactions 的点个上，不可以的点个下……

**Comment by bwtx2022** [comment]
> 那来投个票？觉得可以 reactions 的点个上，不可以的点个下……

建议附上中止人数（

**Comment by abcdesteve** [comment]
> 不建议做，mod manager更新的时候不会检查mod对应的版本，经常炸，而且自动更新之后要是启动不了那还会被甩锅给PCL，大型整合包一般也不会去更新mod，没什么必要

弄个大大的免责声明，然后崩溃分析那里提示回滚mod版本就行了
反正肯定有人用的到
有总比没有好 [doge]

**Comment by bigbird2007** [comment]
那如果有整合包魔改mod，更新完炸了咋办

**Comment by Yizhouuu** [comment]
> 那来投个票？觉得可以 reactions 的点个上，不可以的点个下……

主要是没必要是自动更新呀，检测出哪些需要更新，然后有一个更新的按钮就够了，类似于HMCL（但HMCL的更新有一点问题）

**Comment by Yizhouuu** [comment]
> > 那来投个票？觉得可以 reactions 的点个上，不可以的点个下……
> 
> 主要是没必要是自动更新呀，检测出哪些需要更新，然后有一个更新的按钮就够了，类似于HMCL（但HMCL的更新有一点问题）

然后如果能像mod manager那样识别命名中的标签（例如【前置】architectury识别成architectury带前置标签），然后更新了模组之后自动再加上标签，自动重命名就更好

**Comment by Yizhouuu** [comment]
> 

很多玩家都有很多模组，比如我们自己用的就是两百多个，模组新版本会添加新的东西，修复BUG，肯定是保持最新是最好的。至于说更新会导致不兼容，我目前没遇到过，一般都是旧版本BUG多。
再有，我觉得最主要的是，应该是自动检查更新，然后显示哪些需要更新，再手动选择哪些要更新，而不是全自动，全自动肯定不行
如何识别模组，HMCL、curseforge这些似乎都可以做到，还有mod manager，似乎是根据模组modid和作者提供的地址？可以参考下这些软件

**Comment by LTCatt** [comment]
umm 那这样，换个说法，支持检查 Mod 更新，并可以手动选择更新哪些 Mod（
我重新开个 Issue……
