### ISSUE TITLE
支持 MacOS、Linux、IOS、安卓 等其他操作系统

### ISSUE THREAD

**Issue by LTCatt** [Meloong-Git/PCL#54]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这一功能。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一提案未在投票列表中。
- [X] 我已知晓还没做的新功能真的太多了，忙不过来，所以新功能提案几乎不会被处理，也不建议再提交新功能提案 qwq……

### 描述

允许 PCL2 在 MacOS、Linux 等其他操作系统上使用。

### 原因

由于 PCL2 的底层界面框架（WPF）无法跨系统，要兼容其他系统无异于完全重做，所以这是根本不可能的事情……

不过你可以试试用 wine 之类的玩意儿，听说管用。

**Comment by PlayMcBKuwu** [comment]
> > 不过你可以试试用 wine 之类的玩意儿，听说管用。
> 
> 看到这的，不用试了，我试过了，不行（
> 
> 万能的 deepin-wine 也不行（

尝试安装 Wine-Mono 或者 Wine-Gecko 后再启动，这两个可以支持 WPF。

**Comment by Starry-Sky-World** [comment]
WPF框架似乎可以跨系统（朋友提的:( ）

**Comment by Aelsan5600** [comment]
Mac平台可以使用PCL-Community的PCL Mac，但是该项目还在早期开发阶段，可能不稳定

**Comment by AnemoFlower** [comment]
> Mac平台可以使用PCL-Community的PCL Mac，但是该项目还在早期开发阶段，可能不稳定

10 月 1 日发布第一个稳定的正式版，在这之前欢迎大家来测 bug（
