### ISSUE TITLE
在更新时被防火墙或杀毒软件报毒并删除

### ISSUE THREAD

**Issue by LTCatt** [Meloong-Git/PCL#56]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在 PCL2 更新时，Windows Defender 或卡巴斯基等杀毒软件将 PCL2 识别为病毒，并自动删除。

### 放弃原因

这是由于 PCL2 没有购买数字签名导致的，开发者**没有任何办法**解决这一问题。
你可以将 PCL2 添加到防火墙白名单，这样至少不会被删……
只要你是从官方渠道下载的，或者使用 PCL2 内置更新来更新的，都不是病毒，是误报……

**Comment by Light-Beacon** [comment]
防火墙白名单 x
杀软 信任区/白名单 √
