### ISSUE TITLE
更新下载管理显示失败（Finished）：未设置对象变量或 With 块变量。

### ISSUE THREAD

**Issue by RawDiamondMC** [Meloong-Git/PCL#595]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [ ] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开下载界面，PCL2第一次报错。（日志第365行）点击“反馈”按钮后返回到主页。
![屏幕截图 2022-12-14 171310](https://user-images.githubusercontent.com/112449001/207554880-bac7de3e-3c98-4110-996d-5e52aa42ccf0.png)
12分钟后再次打开下载界面，PCL2第二次报错。（日志第11343行）。点击“取消”，未发现任何问题（也有可能是眼瞎没看见）。

### 重现步骤

下载Curseforge整合包后打开下载界面，PCL2报错。

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10226161/Log1.txt)

**Comment by RawDiamondMC** [comment]
测[#584](github.com/Hex-Dragon/PCL2/issues/584)的时候测出来的问题（

**Comment by LBZiXL** [comment]
和我的#536重复了，不过你好像把重现步骤研究出来了

**Comment by WForst-Breeze** [comment]
与 #536 重复，感谢您的反馈~
