### ISSUE TITLE
关于PCL2的账户安全性问题

### ISSUE THREAD

**Issue by TheXiaoma** [Meloong-Git/PCL#596]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

将PCL2中启动游戏时的账号token日志输出关闭
![D950764C239613213511DF3E0508AE90](https://user-images.githubusercontent.com/90320307/207559210-8f78fa81-a036-4139-a921-43d0979770b1.jpg)

### 原因

因为使用token可以直接登录微软账户
而PCL2的日志中有默认输出了这一项(如图内第6行)
这就导致部分人士在将日志直接发至群内寻求帮助时
将账号暴露在风险之中
有概率被别有用心的人盗刷token 登陆账号
对个人造成损失(服务器被封禁等)

（如果这是MC的日志，或许可以尝试将其删除？我也不清楚

**Comment by WForst-Breeze** [comment]
latest.log是Minecraft输出的日志，已初步确认，感谢您的反馈~

**Comment by WForst-Breeze** [comment]
草，才反应过来，这个是MC在每次游戏结束的时候输出的log，这超出了PCL2的范畴了qwq
