### ISSUE TITLE
大批量下载游戏时出现问题

### ISSUE THREAD

**Issue by shiori02** [Meloong-Git/PCL#648]
### 检查项

- [x] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

大批量下载游戏时完成一部分后出现此bug。
（大批量下载指：一次性下载：1.4、1.5、1.6、1.7、1.8、1.9、1.10、1.11、1.12、1.13、1.14、1.15、1.16、1.17、1.18、1.19）
![image](https://user-images.githubusercontent.com/88921012/208571680-03aa4f44-d932-4abc-a5e7-99ed29dfab65.png)

### 重现步骤

一次性下载了以下游戏版本（原版）：1.4、1.5、1.6、1.7、1.8、1.9、1.10、1.11、1.12、1.13、1.14、1.15、1.16、1.17、1.18、1.19

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10264394/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10264404/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/10264405/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/10264406/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/10264407/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
![image](https://user-images.githubusercontent.com/76810494/208578338-3e6131e3-37af-4f52-99c6-a96fe4e03b2a.jpeg)

**Comment by bwtx2022** [comment]
#536
