### ISSUE TITLE
为背景增加幻灯片功能

### ISSUE THREAD

**Issue by FangFuJi1991** [Meloong-Git/PCL#862]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

可以让用户 按**随机**的方式轮播背景图片 或 按**名称的排序**轮播背景图片，并且可以让用户自定义**显示的时间**。

### 原因

做了一些mc壁纸，每张都觉得好好看OvO，想在里面实现幻灯片的功能，但是没用QwQ，所以我需要这种功能。
如果能做的话就谢谢了(❁´◡`❁)

**Comment by quannen** [comment]
龙猫:工程量不小（笑

**Comment by WForst-Breeze** [comment]
已初步确认，感谢您的反馈~

**Comment by LTCatt** [comment]
太超出启动器的范围了，抱歉（
