### ISSUE TITLE
在设置页面中添加统一修改游戏登录方式的选项

### ISSUE THREAD

**Issue by SuoHouDaiShi** [Meloong-Git/PCL#882]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

在“设置”-“游戏”页面中添加一个“游戏登录方式”的模块，里面可以统一修改游戏的登录方式，比如LittleSkin或者authlib-injector。
比如小明从入正之前一直在用LittleSkin登录，并且下载了很多的游戏版本，都把他们设置成了外置登录，但是小明在过年期间入正了，小明必须一个个在游戏版本设置页面中修改登录方式（我体验过qwq

### 原因

这项优化让我或我的朋友更方便的切换登录方式。
如果没有这项优化，我或我的朋友每次都必须单独设置登录方式，让操作变得很麻烦。
也可以让使用LittleSkin登录的玩家在入正以后更方便的切换登录方式。

**Comment by WForst-Breeze** [comment]
与 #317 类似，感谢您的反馈

**Comment by SuoHouDaiShi** [comment]
> 与 #317 类似，感谢您的反馈

好吧，谢谢www
